# first attempt - simple reverse prediction

In [3]:
# 1️⃣ ייבוא המודול והפונקציות
import functions         # ייבוא רגיל למודול
from functions import *  # ייבוא כל הפונקציות ל־namespace

# 2️⃣ טעינה מחדש
import importlib
importlib.reload(functions)  # מוודא שהמודול מעודכן

# 3️⃣ הרצת הפונקציות שוב ל־namespace
from functions import *  # שוב מייבא את כל הפונקציות אחרי ה־reload

In [ ]:
import numpy as np
import pandas as pd

from read_from_file_df import *
import pickle
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [7]:
SIZE = 10
AMOUNT_BOARDS = 100000
AMOUNT_MOVES = 100
NUM_DICT = 1
gen = 3

In [6]:
reverse_df_sort = load_reverse_df(SIZE, AMOUNT_BOARDS, gen)

KeyboardInterrupt:

In [ ]:
X_train, X_val, X_test, y_train, y_val, y_test = prepare_reverse_dataset(reverse_df_sort, SIZE, gen, target_pixel_index=0, test_size=0.1, val_size=0.1, random_state=365)

dt = tree.DecisionTreeClassifier(random_state=42)
dt = dt.fit(X_train, y_train)

y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

train_test_full_error = pd.concat([measure_error(y_train, y_train_pred, 'train'),
                                measure_error(y_test, y_test_pred, 'test')],
                                axis=1)

print(dt.tree_.node_count, dt.tree_.max_depth)
train_test_full_error

665157 130

              train      test
accuracy   0.999448  0.785625
precision  0.999695  0.488910
recall     0.997668  0.524636
f1         0.998681  0.506143

In [ ]:
depth_to_check = [4,5,6,7,8,9,10,15,20,30,50,100]

for i in depth_to_check:
    dt, node_count, max_depth, train_test_full_error  = dec_tree_df(X_train,y_train, X_test, y_test, i, 42)
    
    name_file = f"{PATH_MODELS}\\reverse_model1\\{SIZE}\\decision_tree_size{SIZE}_reverse_df_model_{str(i)}.pkl"
    with open(name_file, 'wb') as file:
        pickle.dump(dt, file)
    
    print(node_count, max_depth)
    print(train_test_full_error)

31 4
              train      test
accuracy   0.814385  0.813788
precision  0.589749  0.588523
recall     0.371328  0.367980
f1         0.455718  0.452826
63 5
              train      test
accuracy   0.817314  0.816681
precision  0.603180  0.601068
recall     0.371249  0.370250
f1         0.459613  0.458234
127 6
              train      test
accuracy   0.819777  0.819298
precision  0.632253  0.630688
recall     0.331737  0.330608
f1         0.435153  0.433811
255 7
              train      test
accuracy   0.822260  0.821189
precision  0.629341  0.625846
recall     0.366508  0.363146
f1         0.463240  0.459606
511 8
              train      test
accuracy   0.825116  0.824589
precision  0.635219  0.633935
recall     0.385913  0.384051
f1         0.480133  0.478324
1023 9
              train      test
accuracy   0.828615  0.827652
precision  0.646601  0.644167
recall     0.399194  0.395237
f1         0.493633  0.489894
2047 10
              train      test
accuracy   0.832311  0.830953
precision  0.656701  0.652524
recall     0.416312  0.412150
f1         0.509579  0.505202
50485 15
              train      test
accuracy   0.862494  0.835234
precision  0.725176  0.640282
recall     0.552172  0.486371
f1         0.626958  0.552814
267051 20
              train      test
accuracy   0.927786  0.821354
precision  0.872510  0.582083
recall     0.766988  0.520631
f1         0.816353  0.549645
572205 30
              train      test
accuracy   0.990017  0.796153
precision  0.990839  0.512965
recall     0.961183  0.523845
f1         0.975786  0.518348
656399 50
              train      test
accuracy   0.999187  0.786592
precision  0.999450  0.491070
recall     0.996663  0.527455
f1         0.998055  0.508613
665203 100
              train      test
accuracy   0.999448  0.786044
precision  0.999695  0.489815
recall     0.997668  0.524151
f1         0.998681  0.506402

In [ ]:
amount_features = len(reverse_df_sort.columns) - SIZE*SIZE #the previous boards
features = reverse_df_sort.iloc[:, :amount_features]
for i in range(SIZE*SIZE): # to any pixel in the expected board
    name_col = 'Col_' + str(i+amount_features)
    target = reverse_df_sort[name_col]
    X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=613)
    dt, node_count, max_depth, train_test_full_error  = dec_tree_df(X_train,y_train, X_test, y_test, 15, 42)
    name_file = f"{PATH_MODELS}\\reverse1\\{SIZE}\\dt_size{SIZE}_r1_pixel_{str(i+1)}.pkl"
    with open(name_file, 'wb') as file:
        pickle.dump(dt, file)
    print(i)
    print(node_count, max_depth)
    print(train_test_full_error)

NameError: name 'reverse_df_sort' is not defined

In [ ]:
X_test

,Col_0,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,...,Col_15,Col_16,Col_17,Col_18,Col_19,Col_20,Col_21,Col_22,Col_23,Col_24
4827,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
17922,0,1,0,1,1,1,1,1,0,1,...,0,0,1,1,1,0,0,1,1,1
17197,0,1,0,1,0,0,1,0,1,0,...,1,1,1,0,0,1,1,0,0,0
5373,0,0,0,0,0,0,1,1,1,0,...,0,0,0,0,1,0,0,1,1,1
2632,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12395,0,0,1,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
15187,0,1,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,1,0
1518,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
8394,0,0,0,0,1,1,0,1,1,0,...,1,1,0,1,0,0,1,0,0,1
21577,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,1,1,0,0,0

In [ ]:
PATH_DATA_TEST = 'C:\\GameOfLifeFiles\\dataTest\\'

In [ ]:
name_file = f"{PATH_DATA_TEST}\\data_test_size_{SIZE}.pkl"
with open(name_file, 'wb') as file:
    pickle.dump(X_test, file)